from django.urls import path
from . import views

urlpatterns = [
    path('health/', views.health_check_view, name='health_check'),
    path('', views.home_view, name='home'),
    path('privacidad/', views.politica_privacidad_view, name='politica_privacidad'),
    path('terminos/', views.terminos_condiciones_view, name='terminos_condiciones'),
    path('soporte/', views.soporte_view, name='soporte'),
    path('servicios/', views.servicios_view, name='servicios'),
    path('contacto/', views.contacto_view, name='contacto'),
    path('chatbot/', views.chatbot_view, name='chatbot'),
    path('citas/agendar/', views.agendar_cita_view, name='agendar_cita'),
    path('citas/disponibilidad/', views.disponibilidad_horarios_view, name='disponibilidad_horarios'),
    path('citas/mis-citas/', views.mis_citas_view, name='mis_citas'),
    path('citas/<int:cita_id>/calificar/', views.calificar_cita_view, name='calificar_cita'),
    path('citas/<int:cita_id>/pagar/', views.pagar_cita_view, name='pagar_cita'),
    path('citas/<int:cita_id>/pago/simulacion/', views.simular_pago_cita_view, name='simular_pago_cita'),
    path('citas/<int:cita_id>/tarjeta/', views.datafast_widget_view, name='datafast_widget'),
    path('citas/<int:cita_id>/tarjeta/resultado/', views.datafast_result_view, name='datafast_result'),
    path('citas/cancelar/<int:cita_id>/', views.cancelar_cita_view, name='cancelar_cita'),
    path('mascotas/', views.mis_mascotas_view, name='mis_mascotas'),
    path('mascotas/nueva/', views.nueva_mascota_view, name='nueva_mascota'),
    path('mascotas/editar/<int:mascota_id>/', views.editar_mascota_view, name='editar_mascota'),
    path('mascotas/eliminar/<int:mascota_id>/', views.eliminar_mascota_view, name='eliminar_mascota'),
    path('perfil/', views.perfil_cliente_view, name='perfil_cliente'),
    
    # Admin / Staff
    path('gestion/', views.gestion_admin_view, name='gestion_admin'),
    path('gestion/cuentas/', views.cuentas_admin_view, name='cuentas_admin'),
    path('gestion/cuentas/<int:user_id>/eliminar/', views.eliminar_cuenta_sistema_view, name='eliminar_cuenta_sistema'),
    path('gestion/configuracion/', views.configuracion_negocio_view, name='configuracion_negocio'),
    path('gestion/suscripcion/', views.suscripcion_negocio_view, name='suscripcion_negocio'),
    path('gestion/suscripcion/pagar/', views.crear_pago_suscripcion_view, name='crear_pago_suscripcion'),
    path('gestion/suscripcion/pago/<int:pago_id>/tarjeta/', views.datafast_suscripcion_widget_view, name='datafast_suscripcion_widget'),
    path('gestion/suscripcion/pago/<int:pago_id>/resultado/', views.datafast_suscripcion_result_view, name='datafast_suscripcion_result'),
    path('gestion/cita/<int:cita_id>/estado/', views.cambiar_estado_cita_view, name='cambiar_estado_cita'),
    path('gestion/cita/<int:cita_id>/pago/', views.actualizar_pago_cita_view, name='actualizar_pago_cita'),
    path('gestion/cita/<int:cita_id>/seguimiento/', views.actualizar_seguimiento_cita_view, name='actualizar_seguimiento_cita'),
    path('gestion/servicio/nuevo/', views.servicio_form_view, name='nuevo_servicio'),
    path('gestion/servicio/<int:servicio_id>/editar/', views.servicio_form_view, name='editar_servicio'),
    path('gestion/servicio/<int:servicio_id>/toggle/', views.toggle_servicio_view, name='toggle_servicio'),
    path('gestion/sucursal/nueva/', views.sucursal_form_view, name='nueva_sucursal'),
    path('gestion/sucursal/<int:sucursal_id>/editar/', views.sucursal_form_view, name='editar_sucursal'),

    # Auth
    path('registro/', views.registro_view, name='registro'),
    path('login/', views.login_usuario_view, name='login'),
    path('logout/', views.logout_usuario_view, name='logout'),
    path('recuperar-contrasena/', views.solicitar_codigo_recuperacion_view, name='password_reset'),
    path('recuperar-contrasena/verificar/', views.verificar_codigo_recuperacion_view, name='password_reset_verify'),
    path('recuperar-contrasena/nueva-contrasena/', views.establecer_nueva_contrasena_view, name='password_reset_confirm'),
    path('recuperar-contrasena/completado/', views.recuperacion_completada_view, name='password_reset_complete'),
]
