# Generated by Django 6.1 on 2026-08-06 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Confirmación'), ('CONFIRMADA', 'Confirmada'), ('ATENDIDA', 'Servicio Atendido'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de Atención'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(verbose_name='Hora de Atención'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.PositiveIntegerField(default=2, verbose_name='Edad (años)'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL, verbose_name='Dueño/Propietario'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo en catálogo'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('peluqueria', 'Peluquería & Estética'), ('bano', 'Baño & Spa'), ('salud', 'Salud & Higiene'), ('especial', 'Tratamientos Especiales')], default='peluqueria', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción detallada'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=45, verbose_name='Duración estimada (minutos)'),
        ),
    ]
