# Generated by Django 6.1 on 2026-08-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0017_corregir_textos_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='categoria',
            field=models.CharField(default='peluquería y estética para mascotas', max_length=120),
        ),
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='descripcion_footer',
            field=models.TextField(default='Centro especializado en estética, peluquería y spa para mascotas.'),
        ),
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='etiqueta_resenas',
            field=models.CharField(default='Reseñas de clientes', max_length=80),
        ),
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='hero_badge',
            field=models.CharField(default='Peluquería y estética para mascotas', max_length=180),
        ),
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='hero_descripcion',
            field=models.TextField(default='Servicios de higiene y cuidado estético con atención personalizada.'),
        ),
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='hero_titulo',
            field=models.CharField(default='Baño, corte y cariño para tu mascota.', max_length=180),
        ),
    ]
